# Generated by Django 4.2.16 on 2026-03-20 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bill_apply_gst_bill_gst_amount_bill_subtotal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Shree Mahalaxmi Lace', max_length=200)),
                ('address', models.TextField(default='142, Divyanand Society, U.M Road, Near Chosath Jogani Mandir, Surat')),
                ('gstin', models.CharField(default='24AGQPJ2786A1ZF', max_length=20)),
                ('phone', models.CharField(default='9825033599', max_length=20)),
                ('email', models.EmailField(blank=True, default='shreemahalaxmilace@gmail.com', max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('terms', models.TextField(blank=True, default='Goods once sold will not be taken back.')),
            ],
            options={
                'verbose_name': 'Company Profile',
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='cgst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='bill',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='bill',
            name='igst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='bill',
            name='is_igst',
            field=models.BooleanField(default=False, help_text='Inter-state = IGST; Intra-state = SGST+CGST'),
        ),
        migrations.AddField(
            model_name='bill',
            name='sgst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='billitem',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='billitem',
            name='unit',
            field=models.CharField(default='MTR', max_length=10),
        ),
        migrations.AddField(
            model_name='party',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='product',
            name='hsn_code',
            field=models.CharField(blank=True, help_text='HSN/SAC code e.g. 5806', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('PCS', 'PCS'), ('MTR', 'MTR'), ('KG', 'KG'), ('SET', 'SET'), ('BOX', 'BOX'), ('NOS', 'NOS')], default='MTR', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='gst_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
